/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF Page
 #	author : miyako
 #	2017/10/18
 #
 # --------------------------------------------------------------------------------*/



// --- Page
void PDF_SET_ROTATION(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_REMOVE_PAGE(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_EXCHANGE_PAGE(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_INSERT_PAGE(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_GET_PAGE_ANNOTATION(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_GET_TEXT(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_GET_IMAGES(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_GET_DATA(sLONG_PTR *pResult, PackagePtr pParams);
